create table if not exists public.aether_accounts (
    id bigint generated by default as identity primary key,
    username text unique not null,
    password text not null,
    created_at timestamptz not null default now()
);

alter table public.aether_accounts
    add column if not exists username text,
    add column if not exists password text,
    add column if not exists created_at timestamptz default now();

create unique index if not exists aether_accounts_username_key on public.aether_accounts (username);

alter table public.aether_accounts
    alter column created_at set default now();

alter table public.aether_accounts enable row level security;

drop policy if exists anon_select_accounts on public.aether_accounts;
create policy anon_select_accounts
on public.aether_accounts
for select
to anon
using (true);

drop policy if exists anon_insert_accounts on public.aether_accounts;
create policy anon_insert_accounts
on public.aether_accounts
for insert
to anon
with check (true);

-- ══════════════════════════════════════════════
-- GridStore (community apps + moderation overrides)
-- ══════════════════════════════════════════════
create table if not exists public.aether_store_apps (
    id text primary key,
    status text not null default 'pending',
    app jsonb not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.aether_store_overrides (
    app_id text primary key,
    payload jsonb not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create or replace function public.aether_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_updated_at_store_apps on public.aether_store_apps;
create trigger set_updated_at_store_apps
before update on public.aether_store_apps
for each row execute function public.aether_set_updated_at();

drop trigger if exists set_updated_at_store_overrides on public.aether_store_overrides;
create trigger set_updated_at_store_overrides
before update on public.aether_store_overrides
for each row execute function public.aether_set_updated_at();

alter table public.aether_store_apps enable row level security;
alter table public.aether_store_overrides enable row level security;

drop policy if exists anon_select_store_apps on public.aether_store_apps;
create policy anon_select_store_apps
on public.aether_store_apps
for select
to anon
using (true);

drop policy if exists anon_insert_store_apps on public.aether_store_apps;
create policy anon_insert_store_apps
on public.aether_store_apps
for insert
to anon
with check (true);

drop policy if exists anon_update_store_apps on public.aether_store_apps;
create policy anon_update_store_apps
on public.aether_store_apps
for update
to anon
using (true)
with check (true);

drop policy if exists anon_delete_store_apps on public.aether_store_apps;
create policy anon_delete_store_apps
on public.aether_store_apps
for delete
to anon
using (true);

drop policy if exists anon_select_store_overrides on public.aether_store_overrides;
create policy anon_select_store_overrides
on public.aether_store_overrides
for select
to anon
using (true);

drop policy if exists anon_insert_store_overrides on public.aether_store_overrides;
create policy anon_insert_store_overrides
on public.aether_store_overrides
for insert
to anon
with check (true);

drop policy if exists anon_update_store_overrides on public.aether_store_overrides;
create policy anon_update_store_overrides
on public.aether_store_overrides
for update
to anon
using (true)
with check (true);

drop policy if exists anon_delete_store_overrides on public.aether_store_overrides;
create policy anon_delete_store_overrides
on public.aether_store_overrides
for delete
to anon
using (true);

-- ══════════════════════════════════════════════
-- Talky (simple DM messages)
-- ⚠️ Demo policies: anon can read/write.
-- ══════════════════════════════════════════════
create table if not exists public.aether_talky_messages (
    id bigint generated by default as identity primary key,
    convo text not null,
    sender text not null,
    payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists aether_talky_messages_convo_id_idx
on public.aether_talky_messages (convo, id);

alter table public.aether_talky_messages enable row level security;

drop policy if exists anon_select_talky_messages on public.aether_talky_messages;
create policy anon_select_talky_messages
on public.aether_talky_messages
for select
to anon
using (true);

drop policy if exists anon_insert_talky_messages on public.aether_talky_messages;
create policy anon_insert_talky_messages
on public.aether_talky_messages
for insert
to anon
with check (true);

-- â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
-- Aether Music (tracks)
-- âš ï¸ Demo policies: anon can read/write.
-- â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
create table if not exists public.aether_music_tracks (
    id bigint generated by default as identity primary key,
    owner text not null,
    title text not null,
    artist text not null,
    description text not null default '',
    type text not null default 'single',
    album text,
    track_number int,
    audio_data text,
    cover_data text,
    plays int not null default 0,
    likes int not null default 0,
    created_at timestamptz not null default now()
);

create index if not exists aether_music_tracks_created_at_idx
on public.aether_music_tracks (created_at desc);

alter table public.aether_music_tracks enable row level security;

drop policy if exists anon_select_music_tracks on public.aether_music_tracks;
create policy anon_select_music_tracks
on public.aether_music_tracks
for select
to anon
using (true);

drop policy if exists anon_insert_music_tracks on public.aether_music_tracks;
create policy anon_insert_music_tracks
on public.aether_music_tracks
for insert
to anon
with check (true);

drop policy if exists anon_update_music_tracks on public.aether_music_tracks;
create policy anon_update_music_tracks
on public.aether_music_tracks
for update
to anon
using (true)
with check (true);

drop policy if exists anon_delete_music_tracks on public.aether_music_tracks;
create policy anon_delete_music_tracks
on public.aether_music_tracks
for delete
to anon
using (true);
